[project]
name = "assignment2-cnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "torch>=2.9.0",
]
# toml file is ingredients
# uv.lock file is recipe 